version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8  
  pre_build:
    commands:
    - apt-get update
    - apt-get -y install libaio1
  build:
    commands:
    - mvn clean install
  post_build:
    commands:
artifacts:
  files:
  - 03-spring-boot-web-application-h2-0.0.1-SNAPSHOT.war